// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroConDetalle.DAL;

namespace RegistroConDetalle.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211016034820_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RegistroConDetalle.Entidades.Permisos", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Veces_Asignado")
                        .HasColumnType("INTEGER");

                    b.HasKey("PermisoId");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            PermisoId = 2,
                            Descripcion = "Para poder salir si te sientes mal",
                            Nombre = "Permiso por malestares",
                            Veces_Asignado = 0
                        },
                        new
                        {
                            PermisoId = 3,
                            Descripcion = "Para que el trabajador pueda estudiar",
                            Nombre = "Permiso para estudiar",
                            Veces_Asignado = 0
                        });
                });

            modelBuilder.Entity("RegistroConDetalle.Entidades.Roles", b =>
                {
                    b.Property<int>("RoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("esActivo")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoiId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RegistroConDetalle.Entidades.RolesDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePermiso")
                        .HasColumnType("TEXT");

                    b.Property<int>("PermisoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("esAsignado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoiId");

                    b.ToTable("RolesDetalle");
                });

            modelBuilder.Entity("RegistroConDetalle.Entidades.RolesDetalle", b =>
                {
                    b.HasOne("RegistroConDetalle.Entidades.Roles", null)
                        .WithMany("RolesDetalle")
                        .HasForeignKey("RoiId");
                });

            modelBuilder.Entity("RegistroConDetalle.Entidades.Roles", b =>
                {
                    b.Navigation("RolesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
